apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: microservice-demo
    name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: microservice-demo
    name: postgres-pod
