apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: microservice-demo
    name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: microservice-demo
    name: redis-pod
