apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: microservice-demo
    name: redis-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
