apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: microservice-demo
    name: result-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: microservice-demo
    name: result-app-pod
