apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    app: microservice-demo
    name: worker-app-pod
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker
